server:
  port: 8888


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_project?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ydg@971810252
    driver-class-name: com.mysql.jdbc.Driver
  output:
    ansi:
      enabled: always
  application:
    name: myproject


cloud:
  security:
    protected:
      url: /bean/test;/sysUser/**;
    expiration: 200000000 #单位是毫秒
    signKey: my_project
    permitUrl: /login


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    #如果类中加了@TableId(value = "id", type = IdType.UUID)中的type那么会优先使用类上的id生成策略
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    refresh-mapper: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
